version: '3'
services:
  test:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm test

  lint:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run lint

  coverage:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm test -- --coverage

volumes:
  node_modules: