version: '3.8'

services:
  base:
    build:
      context: ..
      dockerfile: test_config/Dockerfile
    image: saveit-test
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - CI=true
      - npm_config_yes=true
    
  test:
    extends: base
    command: npm test
    
  lint:
    extends: base
    command: npm run lint
    
  coverage:
    extends: base
    command: node_modules/.bin/vitest run --coverage
    volumes:
      - ..:/app
      - ../coverage:/app/coverage
    