name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: saveit-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run ESLint
      run: docker run --rm saveit-test npm run lint

    - name: Run tests
      run: docker run --rm saveit-test npm test

    - name: Generate coverage report
      run: |
        mkdir -p coverage
        docker run --rm -v ${{ github.workspace }}/coverage:/app/coverage saveit-test npm test -- --coverage --coverageReporters=lcov
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}